version: '3'

services:
  messagebus:
    image: rabbitmq:3-management
    volumes:
      - messagebus_data:/data/messagebus_devops
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db_devops
    ports:
      - "27017:27017"

  register-service:
    build: Microservices/register-service
    ports:
      - "3001:3001"
    env_file:
      docker.env
    environment:
      - DOCKERPORT=3001
    depends_on:
      - mongo
      - messagebus

  login-service:
    build: ./Microservices/login-service
    ports:
      - "3002:3002"
    env_file:
      docker.env
    environment:
      - DOCKERPORT=3002
    depends_on:
      - mongo
      - messagebus

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  alertmanager:
    build:
      context: ./alertmanager
      dockerfile: Dockerfile
    ports:
      - "9093:9093"

volumes:
  mongodb_data:
  messagebus_data:
  prometheus-data:


