openapi: "3.0.0"
info:
  title: Webs5 API
  description: This is the API documentation for the Webs5 project.
  version: 1.0
tags:
  - name: Authentication
    description: API endpoints for user authentication

paths:
  /api/register:
    post:
      tags: [ Authentication ]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  example: "owner"
                  type: string
                password:
                  example: "password"
                  type: string
                email:
                  example: "nepEmail@Email.com"
                  type: string
                role:
                  example: "owner"
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad Json request - missing username, password, email or role
        '409':
          description: Conflict - if parameter is already in use
        '500':
          description: Internal server error
        '503':
          description: Service is unavailable