groups:
  - name: DemoAlerts
    rules:
      - alert: "On gateway down"
        expr: up{job="api_gateway"} < 1
        for: 30s
      - alert: "On login down"
        expr: up{job="login_service"} < 1
        for: 30s
      - alert: "On register down"
        expr: up{job="register_service"} < 1
        for: 30s