global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "register_service"
    static_configs:
      - targets: [ "register_service:3001" ]
  - job_name: "login_service"
    static_configs:
      - targets: [ "login_service:3002" ]
  - job_name: "api_gateway"
    static_configs:
      - targets: [ "api_gateway:5000" ]
