global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "register-service"
    static_configs:
      - targets: [ "register-service:3001" ]
  - job_name: "login-service"
    static_configs:
      - targets: [ "login-service:3002" ]
