openapi: "3.0.0"
info:
  title: Webs5 API
  description: This is the API documentation for the Webs5 project.
  version: 1.0
tags:
  - name: Authentication
    description: API endpoints for user authentication
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  security:
    - bearerAuth: [ ]

paths:

  /api/login:
    post:
      tags: [ Authentication ]
      summary: Authenticate user and generate JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  example: "owner"
                  type: string
                password:
                  example: "password"
                  type: string
      responses:
        '200':
          description: JWT token generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Bad Json request - missing username, password
        '401':
          description: Conflict - invalid username, password or email not verified
        '500':
          description: Internal server error
        '503':
          description: Service is unavailable

  /api/logout:
    delete:
      tags: [ Authentication ]
      summary: Delete token and logout
      security:
        - bearerAuth: [ ]
      responses:
        '204':
          description: Token is removed and you cannot access the service anymore
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
        '503':
          description: Service is unavailable

  /api/token:
    post:
      tags: [ Authentication ]
      summary: Get new token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        '201':
          description: JWT token generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Bad Json request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
        '503':
          description: Service is unavailable

  /api/verifyAccount:
    patch:
      tags: [ Authentication ]
      summary: lets the user fill in the verifyToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  example: "owner"
                  type: string
                token:
                  example: "token"
                  type: string
      responses:
        '200':
          description: ok
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
        '503':
          description: Service is unavailable

  /api/getVerifyStatus/:
    get:
      tags: [ Authentication ]
      summary: retrieves the verification status for a given username
      parameters:
        - in: query
          name: username
          schema:
            type: string
          example: "owner"
          required: true
      responses:
        '200':
          description: OK and returns verification status
          content:
            application/json:
              schema:
                type: object
                properties:
                  verified:
                    type: boolean
                  verifyToken:
                    type: string
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
        '503':
          description: Service is unavailable
