version: '3.9'

services:
  api:
    build: ./chatapi
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    volumes:
      - ./chatapi:/usr/src/app
      - /usr/src/app/node_modules
  grafana:
    build: ./grafana
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus-data: